using System.Diagnostics;
using System.IO;
using System.Net.Http;
using System.Security.Cryptography;
using System.Text;
using HanabePhotoManager.Core.Cloud;
using HanabePhotoManager.Infrastructure.Cloud;

namespace HanabePhotoManager.App.Services;

/// <summary>
/// Coordinates Baidu OAuth configuration and the persisted token/session store for the
/// cloud connection section on the Settings page.
///
/// Strict rules from the project hand-off:
///   * AppKey / SecretKey are user-supplied and stored only on this machine. The secret is
///     protected with Windows DPAPI (CurrentUser scope) before being written to settings.
///   * Access / refresh tokens, cookies, OTPs, QR contents and passwords are never placed
///     in logs, source code or non-DPAPI files.
///   * Quark has no public OAuth/netdisk API. We never perform packet capture, private API
///     calls, cookie reuse, QR/OTP automation or client reverse engineering. Quark stays an
///     official web/client handoff that opens the user's real Quark client in a browser.
/// </summary>
public sealed class CloudConnectionSettingsService
{
    public const string QuarkOfficialUrl = "https://pan.quark.cn/";
    public const string BaiduOpenConsoleUrl = "https://pan.baidu.com/union/console";
    public const string BaiduHelpUrl = "https://pan.baidu.com/union/manage/apps";

    private readonly AppSettingsStore _settingsStore;
    private readonly Func<HttpClient> _httpClientFactory;
    private readonly Func<string, ICloudSessionStore> _sessionStoreFactory;
    private readonly Func<byte[], byte[], byte[]> _protect;
    private readonly Func<byte[], byte[], byte[]> _unprotect;
    private readonly string _appDataDirectory;
    // A single, long-lived BaiduOAuthClient is required so that the OAuth `state`
    // nonce generated by BuildAuthorizeUri is still tracked in the client's internal
    // pending-state set when ExchangeCodeAsync runs on completion.
    private readonly Lazy<BaiduOAuthClient> _baiduClient;
    private CloudAuthToken? _pendingBaiduToken;
    private string? _pendingBaiduState;

    public CloudConnectionSettingsService(
        AppSettingsStore? settingsStore = null,
        Func<HttpClient>? httpClientFactory = null,
        Func<string, ICloudSessionStore>? sessionStoreFactory = null,
        string? appDataDirectory = null,
        Func<byte[], byte[], byte[]>? protect = null,
        Func<byte[], byte[], byte[]>? unprotect = null)
    {
        _settingsStore = settingsStore ?? new AppSettingsStore();
        _httpClientFactory = httpClientFactory ?? (() => new HttpClient());
        _sessionStoreFactory = sessionStoreFactory ?? (path => new EncryptedCloudSessionStore(path));
        _appDataDirectory = appDataDirectory
            ?? Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), "HanabePhotoManager", "Cloud");
        Directory.CreateDirectory(_appDataDirectory);
        _protect = protect ?? DefaultProtect;
        _unprotect = unprotect ?? DefaultUnprotect;
        _baiduClient = new Lazy<BaiduOAuthClient>(() => new BaiduOAuthClient(_httpClientFactory()));
    }

    public string SessionStorePath => Path.Combine(_appDataDirectory, "cloud-session.dat");

    public async Task<CloudConnectionSnapshot> LoadAsync(CancellationToken cancellationToken = default)
    {
        var settings = await _settingsStore.LoadAsync(cancellationToken).ConfigureAwait(false);
        var store = _sessionStoreFactory(SessionStorePath);
        CloudAuthToken? baiduToken = null;
        try
        {
            baiduToken = await store.LoadAsync(CloudProviderKind.Baidu, cancellationToken).ConfigureAwait(false);
        }
        catch
        {
            // Corrupt or missing session file is treated as "not connected".
            baiduToken = null;
        }

        return new CloudConnectionSnapshot(
            BaiduAppKey: settings.BaiduAppKey,
            HasBaiduAppSecret: !string.IsNullOrWhiteSpace(settings.BaiduAppSecretProtected),
            BaiduToken: baiduToken);
    }

    public async Task SaveBaiduCredentialsAsync(
        string appKey,
        string appSecret,
        CancellationToken cancellationToken = default)
    {
        var settings = await _settingsStore.LoadAsync(cancellationToken).ConfigureAwait(false);
        settings.BaiduAppKey = string.IsNullOrWhiteSpace(appKey) ? null : appKey.Trim();
        settings.BaiduAppSecretProtected = string.IsNullOrWhiteSpace(appSecret)
            ? null
            : Convert.ToBase64String(_protect(Encoding.UTF8.GetBytes(appSecret.Trim()), null!));
        await _settingsStore.SaveAsync(settings, cancellationToken).ConfigureAwait(false);
    }

    public string? TryReadBaiduAppSecret()
    {
        var settings = _settingsStore.LoadAsync().GetAwaiter().GetResult();
        if (string.IsNullOrWhiteSpace(settings.BaiduAppSecretProtected))
        {
            return null;
        }

        try
        {
            var plain = _unprotect(Convert.FromBase64String(settings.BaiduAppSecretProtected), null!);
            return Encoding.UTF8.GetString(plain);
        }
        catch
        {
            return null;
        }
    }

    public (Uri AuthorizeUri, string State) StartBaiduAuthorization(string appKey)
    {
        if (string.IsNullOrWhiteSpace(appKey))
        {
            throw new ArgumentException("百度网盘 AppKey 是必需的，请先在设置中填写。", nameof(appKey));
        }

        var state = GenerateState();
        _pendingBaiduState = state;
        _pendingBaiduToken = null;

        var uri = _baiduClient.Value.BuildAuthorizeUri(appKey.Trim(), state);
        return (uri, state);
    }

    public async Task<CloudAuthToken> CompleteBaiduAuthorizationAsync(
        string authorizationCode,
        string appKey,
        string appSecret,
        string state,
        CancellationToken cancellationToken = default)
    {
        if (string.IsNullOrWhiteSpace(authorizationCode))
        {
            throw new ArgumentException("授权码是必需的，请在浏览器中复制百度返回的代码。", nameof(authorizationCode));
        }
        if (string.IsNullOrWhiteSpace(appKey) || string.IsNullOrWhiteSpace(appSecret))
        {
            throw new ArgumentException("AppKey 和 AppSecret 是完成授权必需的。");
        }
        if (string.IsNullOrWhiteSpace(state) || !string.Equals(state, _pendingBaiduState, StringComparison.Ordinal))
        {
            throw new InvalidOperationException("授权请求已过期或状态不匹配，请重新打开授权链接。");
        }

        var token = await _baiduClient.Value.ExchangeCodeAsync(
            authorizationCode.Trim(),
            appKey.Trim(),
            appSecret.Trim(),
            state,
            cancellationToken).ConfigureAwait(false);

        var store = _sessionStoreFactory(SessionStorePath);
        await store.SaveAsync(token, cancellationToken).ConfigureAwait(false);
        _pendingBaiduToken = token;
        _pendingBaiduState = null;
        return token;
    }

    public async Task DisconnectBaiduAsync(CancellationToken cancellationToken = default)
    {
        var store = _sessionStoreFactory(SessionStorePath);
        await store.DeleteAsync(CloudProviderKind.Baidu, cancellationToken).ConfigureAwait(false);
        _pendingBaiduToken = null;
        _pendingBaiduState = null;
    }

    public void OpenInBrowser(Uri uri)
    {
        Process.Start(new ProcessStartInfo(uri.AbsoluteUri) { UseShellExecute = true });
    }

    private static string GenerateState()
    {
        Span<byte> buffer = stackalloc byte[24];
        RandomNumberGenerator.Fill(buffer);
        return Convert.ToBase64String(buffer)
            .Replace('+', '-')
            .Replace('/', '_')
            .TrimEnd('=');
    }

    private static byte[] DefaultProtect(byte[] plaintext, byte[]? entropy)
    {
        return ProtectedData.Protect(plaintext, entropy, DataProtectionScope.CurrentUser);
    }

    private static byte[] DefaultUnprotect(byte[] ciphertext, byte[]? entropy)
    {
        return ProtectedData.Unprotect(ciphertext, entropy, DataProtectionScope.CurrentUser);
    }
}

public sealed record CloudConnectionSnapshot(
    string? BaiduAppKey,
    bool HasBaiduAppSecret,
    CloudAuthToken? BaiduToken)
{
    public bool BaiduCredentialsConfigured => !string.IsNullOrWhiteSpace(BaiduAppKey) && HasBaiduAppSecret;
    public bool BaiduAuthorized => BaiduCredentialsConfigured && BaiduToken is not null;
}
